apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - tokens.yaml
  - saml-idp-certificate.yaml

# Default VaultAuth configuration
#
  - auth/vault-auth.yaml

# Facilitate kustomization name updating
#
configurations:
  - auth/kustomizeconfig.yaml