apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: scheduler-web
  template:
    spec:
      containers:
        - name: scheduler-web
          envFrom:
          - secretRef:
              name: auth-signing-key
          - secretRef:
              name: saml-idp-certificate
          - secretRef:
              name: local-user-credentials
          - secretRef:
              name: auth-signing-key
          - configMapRef:
              name: elasticapm-config
          - configMapRef:
              name: api-config
          - configMapRef:
              name: saml-config
          env:
            - name: ELASTIC_APM_SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: elasticapm-config
                  key: ELASTIC_APM_SERVICE_NAME
