apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: scheduler-web
  template:
    metadata:
      annotations:
        vault.hashicorp.com/role: "scheduler-web-kubeauthbot-latest"
        config.linkerd.io/skip-outbound-ports: "443"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-config: "web-apps/data/scheduler-web"
        vault.hashicorp.com/agent-inject-template-config: |
          {{ with secret "web-apps/data/scheduler-web" -}}
          JWT_TOKEN_SIGNING_KEY="{{ .Data.data.JWT_TOKEN_SIGNING_KEY }}"
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-saml-idp-certificate.crt: "ltc-infrastructure/data/keycloak/realm-config"
        vault.hashicorp.com/agent-inject-template-saml-idp-certificate.crt: |
          {{ with secret "ltc-infrastructure/data/keycloak/realm-config" -}}
          {{ .Data.data.SAML_IDP_CERTIFICATE }}
          {{- end }}
    spec:
      containers:
        - name: scheduler-web
          env:
            - name: ELASTIC_APM_SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: elasticapm-config
                  key: ELASTIC_APM_SERVICE_NAME
