apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - public-endpoint.yaml
commonLabels:
  environment: latest
# Prefix/Suffix required for VaultAuth configuration
#
namePrefix: scheduler-web-
nameSuffix: -latest
# Teach kustomize how to update generated names
#
configurations:
  - kustomizeconfig.yaml
commonAnnotations:
  version: 2.2.0-9a6bd35f--2024-07-08.1720460497 # {"$imagepolicy": "openlab-scheduler:scheduler-web-image-policy-latest:tag"}
images:
  - name: "scheduler-web"
    newName: "registry.ltc.bcit.ca/web-apps/openlab-scheduler/scheduler-web"
    newTag: "2.2.0-9a6bd35f--2024-07-08.1720460497" # {"$imagepolicy": "openlab-scheduler:scheduler-web-image-policy-latest:tag"}
patches:
  # Patches ingress hostname with "latest--" prefix
  - target:
      kind: Ingress
      name: ingress
    path: ingress-patch.yaml
  # Patches deployment with secrets
  - target:
      kind: Deployment
    path: deployment-patch.yaml
  # Incorporate vault-secrets
  #
  # adds `-latest` suffix to VaultAuth `spec.mount`
  - target:
      kind: VaultAuth
    path: vault-secrets-latest/vault-auth-patch.yaml
components:
  # Include environment-specific secrets
  - ./vault-secrets-latest
  # Required for VaultAuth role and serviceaccounts
  - ../../base/components/vault-auth
configMapGenerator:
  # Updates elasticapm config
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVICE_NAME=scheduler-web-latest
    behavior: merge
  # Alternate API backend location
  - name: api-config
    literals:
      - API_URL=https://latest--scheduler-api.ltc.bcit.ca/api/
    behavior: merge
  # SAML config
  #
  # Alternate Keycloak SAML idP
  # - name: saml-config
  #   literals:
  #     - SAML_IDENTITY_PROVIDER_URL=https://latest--keycloak.ltc.bcit.ca/realms/ltc/protocol/saml
  # Environments use unique issuers; value should match KEYCLOAK_CLIENT in `create-saml-client` script
  - name: saml-config
    literals:
      - SAML_ISSUER=scheduler-web-latest
    behavior: merge
# Replace APP_URL with "latest" public endpoint
replacements:
  - source:
      kind: Ingress
      name: ingress
      fieldPath: spec.rules.0.host
    targets:
      - select:
          kind: Deployment
        fieldPaths:
          - spec.template.spec.containers.0.env.[name=APP_URL].value
        options:
          delimiter: "/"
          index: 2
