apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openlab-scheduler
resources:
  - ../../base
# Resource names in a shared namespace must be unique
#
namePrefix: scheduler-web-
commonLabels:
  environment: latest
commonAnnotations:
  version: 1.0.7-aef6b528--2023-09-27.1695795388 # {"$imagepolicy": "openlab-scheduler:scheduler-web-image-policy:tag"}
images:
  - name: "scheduler-web"
    newName: "registry.ltc.bcit.ca/web-apps/openlab-scheduler/scheduler-web"
    newTag: "1.0.7-aef6b528--2023-09-27.1695795388" # {"$imagepolicy": "openlab-scheduler:scheduler-web-image-policy:tag"}
# Patches ingress with "latest--" and deployment with annotations
#
patches:
  - target:
      kind: Ingress
    path: ingress-patch.yaml
  - target:
      kind: Deployment
    path: deployment-patch.yaml
configMapGenerator:
  # Updates elasticapm config
  #
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVICE_NAME=scheduler-web-latest
    behavior: merge
# Inject secrets from Vault Secrets Operator
#    
components:
  - ./vault-secrets
