version: "3.9"

services:

  app:
    image: scheduler-web
    build: 
      context: .
      args:
        - VERSION=dev
    command:
      - /bin/sh
      - -c
      - |
        (cd /app/client && npm install)
        (cd /app/client && npm run build)
        npm install
        npm start
    environment:
      - INITIAL_USER=admin
      - INITIAL_PASSWORD=password123
      - API_URL=http://host.docker.internal:8000/api/
      - TZ=America/Vancouver
      - SECRET_KEY=ahuaejsdb
      - SAML_URL=http://localhost:8080/simplesaml/saml2/idp/SSOService.php
    volumes:
      - .:/app
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - test-web-network

  idp:
    image: kenchan0130/simplesamlphp
    ports:
      - "8080:8080"
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: localhost
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://localhost:9000/login/callback
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: http://localhost:9000/logout/callback
    volumes:
      - ./local_saml_config/authsources.php:/var/www/simplesamlphp/config/authsources.php
    networks:
      - test-web-network

  # test:
  #   build:
  #     dockerfile: Dockerfile.playwright
  #     args:
  #       - TEST_USER=root
  #   # TODO: the url prefix after http is dependent on the name of the container for the frotend
  #   environment:
  #     - URL_FRONTEND=http://scheduler-web-app-1:9000
  #   restart: on-failure
  #   # depends_on:
  #   #   app:
  #   #     condition: service_healthy
  #   networks:
  #     - test-web-network

networks:
  test-web-network:
    driver: bridge
