version: "3.9"

services:

  app:
    image: scheduler-web
    build: 
      context: .
      args:
        - VERSION=dev
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npm start
    environment:
      - LOCAL_USER=admin
      - LOCAL_PASSWORD=password123
      - API_URL=http://host.docker.internal:8000/api/
      - TZ=America/Vancouver
      - JWT_TOKEN_SIGNING_KEY=ahuaejsdb
      - SAML_CLIENT_ID=localhost
      - SAML_CALLBACK_URL=http://localhost:9000/login/callback
      # - SAML_URL=https://keycloak.ltc.bcit.ca/realms/dev/protocol/saml
      - SAML_URL=http://localhost:8080/simplesaml/saml2/idp/SSOService.php

    volumes:
      - .:/app
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - test-web-network
    depends_on:
      frontend-builder:
        condition:  service_completed_successfully


  idp:
    image: kenchan0130/simplesamlphp
    ports:
      - "8080:8080"
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: localhost
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://localhost:9000/login/callback
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: http://localhost:9000/logout/callback
    volumes:
      - ./saml/authsources.php:/var/www/simplesamlphp/config/authsources.php
    networks:
      - test-web-network

  # test:
  #   build:
  #     dockerfile: Dockerfile.playwright
  #     args:
  #       - TEST_USER=root
  #   # TODO: the url prefix after http is dependent on the name of the container for the frotend
  #   environment:
  #     - URL_FRONTEND=http://scheduler-web-app-1:9000
  #   restart: on-failure
  #   # depends_on:
  #   #   app:
  #   #     condition: service_healthy
  #   networks:
  #     - test-web-network

  frontend-builder:
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npm run build
    image: node:19.4.0-alpine
    working_dir: /app
    volumes:
      - ./client:/app
      # - data:/code/frontend/build/:rw

networks:
  test-web-network:
    driver: bridge
