version: "3.9"

services:

  app:
    image: scheduler-web
    build: 
      context: .
      args:
        - VERSION=dev
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npm start
    environment:
      # api-config
      - API_URL=http://host.docker.internal:8000/api/

      # saml-config
      # SAML_URL: https://keycloak.ltc.bcit.ca/realms/dev/protocol/saml
      - SAML_URL=http://localhost:8080/simplesaml/saml2/idp/SSOService.php

      # admin-credentials
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password123

      # auth-signing-key
      - JWT_AUTH_SIGNING_KEY=insecureT0kenSigningKey

      # saml-idp-certificate
      # SAML_IDP_CERTIFICATE set in `docker-entrypoint.sh` (uses default `/saml/idp.crt`)

      # simplesaml-config
      - TZ=America/Vancouver
      - SAML_ISSUER=localhost
      - SAML_CALLBACK_URL=http://localhost:9000/login/callback

    volumes:
      - .:/app
    ports:
      - 9000:9000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - test-web-network
    depends_on:
      frontend-builder:
        condition:  service_completed_successfully


  idp:
    image: kenchan0130/simplesamlphp
    ports:
      - 8080:8080
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: localhost
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://localhost:9000/auth/login/callback
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: http://localhost:9000/auth/logout/callback
    volumes:
      - ./saml/authsources.php:/var/www/simplesamlphp/config/authsources.php
      - ./saml/idp.crt:/var/www/simplesamlphp/config/idp.crt
    networks:
      - test-web-network

  frontend-builder:
    image: node:19.4.0
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npm run build
    working_dir: /app
    volumes:
      - ./client:/app

networks:
  test-web-network:
    driver: bridge
