# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

version: "3.9"

services:

  app:
    image: scheduler-web
    build:
      context: .
      args:
        - VERSION=dev
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npm run dev
    environment:
      # api-config
      - API_URL=http://host.docker.internal:8000/api/

      # local saml-config
      - APP_URL=http://localhost:9000/
      - SAML_IDENTITY_PROVIDER_URL=http://localhost:8080/simplesaml/saml2/idp/SSOService.php
      - SAML_ISSUER=localhost

      # auth-signing-key
      - JWT_AUTH_SIGNING_KEY=insecureT0kenSigningKey

      # simplesaml-config
      - TZ=America/Vancouver

    volumes:
      - ./:/app
    ports:
      - "9000:9000"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9000 || exit 1" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - openlab-scheduler-network
    # depends_on:
    #   frontend-builder:
    #     condition: service_completed_successfully

  # idp:
  #   image: kenchan0130/simplesamlphp
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - SIMPLESAMLPHP_SP_ENTITY_ID=localhost
  #     - SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE=http://localhost:9000/auth/login/callback
  #     - SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE=http://localhost:9000/auth/logout/callback
  #   volumes:
  #     - ./saml/authsources.php:/var/www/simplesamlphp/config/authsources.php

  #     # mount saml-idp-certificate
  #     - ./saml/idp.crt:/var/www/simplesamlphp/config/idp.crt
  #   networks:
  #     - openlab-scheduler-network

  # frontend-builder:
  #   image: node:19.4.0
  #   command:
  #     - /bin/sh
  #     - -c
  #     - |
  #       npm install
  #       npm run build
  #   working_dir: /app
  #   volumes:
  #     - ./client:/app

  # jsdoc_builder:
  #   image: node:21-alpine
  #   command:
  #     - /bin/sh
  #     - -c
  #     - |
  #       ./node_modules/.bin/jsdoc -c ./jsdoc.conf.json -r
  #   working_dir: /build
  #   volumes:
  #     - .:/build
  #   depends_on:
  #     app:
  #       condition: service_started

networks:
  openlab-scheduler-network:
