version: "3.9"

services:
  db:
    image: mariadb
    environment:
      - 'MARIADB_ROOT_PASSWORD=isajrqwoihjwaor'
      - 'MARIADB_USER=bsnmysql'
      - 'MARIADB_PASSWORD=bcitbsn491'
      - 'MARIADB_DATABASE=bsn-openlab-scheduler'
    healthcheck:
      test: ["CMD-SHELL", "mysql $$MARIADB_DATABASE -u$$MARIADB_USER -p$$MARIADB_PASSWORD -e 'SELECT 1;'  || exit 1"]
      timeout: 5s
      retries: 10
    volumes:
      - web_data:/var/lib/mysql


  app:
    command:
      - /bin/sh
      - -c
      - |
        (cd /app/client && npm install)
        (cd /app/client && npm run build)
        npm install
        npm start
    build: .
    ports:
      - "8080:8080"
    environment:
      - TZ=America/Vancouver
      - SECRET_KEY=ahuaejsdb
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - .:/app

volumes:
  web_data: