apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: scheduler-web
  template:
    spec:
      containers:
        - name: scheduler-web
# Keycloak realm cert is provisioned by the ci/cd pipeline when the
#   GitLab project settings > CI/CD variable `KEYCLOAK_ENABLED=true`
          volumeMounts:
            - name: keycloak-realm-cert
              mountPath: /app/saml/certs
              readOnly: true
      volumes:
      - name: keycloak-realm-cert
        secret:
          secretName: keycloak-realm-cert
