apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: scheduler-web
  template:
    spec:
      containers:
        - name: scheduler-web
          envFrom:
            - secretRef:
                name: vault-secrets-override
            - secretRef:
                name: oidc-secret
            - configMapRef:
                name: oidc-config
          ports:
            - containerPort: 9000
              protocol: TCP
