apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: scheduler-web
  template:
    spec:
      containers:
        - name: scheduler-web
          envFrom:
            - secretRef:
                name: vault-secrets-override
            - configMapRef:
                name: oidc-config
          env:
            - name: SAML_URL
              value: "https://review--45-keycloak--scheduler-web.ltc.bcit.ca/realms/realm1/broker/saml/endpoint"
          ports:
            - containerPort: 9000
              protocol: TCP
          volumeMounts:
            - name: idp-cert
              mountPath: "/app/saml/certs"
              readOnly: true
      volumes:
      - name: idp-cert
        secret:
          secretName: idp-cert