# adds secrets to deployment
#
---
- op: add
  path: /spec/template/spec/containers/0/envFrom/-
  value:
    secretRef:
      name: admin-credentials

- op: add
  path: /spec/template/spec/containers/0/envFrom/-
  value:
    secretRef:
      name: auth-signing-key

# removes elastic-apm-config
- op: remove
  path: /spec/template/spec/containers/0/envFrom/0
