apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: scheduler-web
  template:
    spec:
      containers:
        - name: scheduler-web
          envFrom:
            - secretRef:
                name: vault-secrets-override
          env:
            - name: SAML_URL
              value: "http://localhost:8080/simplesaml/saml2/idp/SSOService.php"
          ports:
            - containerPort: 9000
              protocol: TCP
