apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: scheduler-web
  template:
    spec:
      containers:
        - name: scheduler-web
          envFrom:
            - secretRef:
                name: vault-secrets-override
          env:
            - name: SAML_URL
              value: "http://localhost:8080/simplesaml/saml2/idp/SSOService.php"
          ports:
            - containerPort: 9000
              protocol: TCP
          volumeMounts:
            - name: idp-cert
              mountPath: "/app/saml/certs"
              readOnly: true
        - name: idp
          image:  kenchan0130/simplesamlphp
          env:
          - name: SIMPLESAMLPHP_SP_ENTITY_ID
            value: "localhost"
          - name: SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE
            value: "http://localhost:9000/login/callback"
          - name: SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE
            value: "http://localhost:9000/logout/callback"
      volumes:
      - name: idp-cert
        secret:
          secretName: idp-cert