apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: scheduler-web
  template:
    spec:
      containers:
        - name: scheduler-web
          env:
            - name: SAML_URL
              valueFrom:
                configMapKeyRef:
                  name: saml-config
                  key: SAML_URL
            - name: SAML_ISSUER
              valueFrom:
                configMapKeyRef:
                  name: saml-config
                  key: SAML_ISSUER
            - name: SAML_CALLBACK_URL
              valueFrom:
                configMapKeyRef:
                  name: saml-config
                  key: SAML_CALLBACK_URL
            - name: SAML_IDP_CERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: saml-idp-certificate
                  key: SAML_IDP_CERTIFICATE
          ports:
            - containerPort: 9000
              protocol: TCP
