apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: scheduler-web
      tier: frontend
  template:
    spec:
      containers:
        - name: scheduler-web
          # injected by ci/cd pipeline when KEYCLOAK_ENABLED is true
          #
          env:
            - name: SAML_IDP_CERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: saml-idp-certificate
                  key: SAML_IDP_CERTIFICATE
