apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: scheduler-web
  template:
    spec:
      containers:
        - name: scheduler-web
          envFrom:
            - secretRef:
                name: vault-secrets-override
            - configMapRef:
                name: saml-config
          ports:
            - containerPort: 9000
              protocol: TCP
          volumeMounts:
            - name: idp-cert
              mountPath: "/app/saml/certs"
              readOnly: true
            - name: idp-pvkey
              mountPath: "/app/saml/secrets"
              readOnly: true
      volumes:
      - name: idp-cert
        secret:
          secretName: idp-cert
      - name: idp-pvkey
        secret:
          secretName: idp-pvkey