apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Flux envsubst replaces variables found in `deploy-vars.env` or falls back to defaults
#
namespace: ${DEPLOY_NAMESPACE:=scheduler-web}

commonLabels:
  environment: review

# Prefix/Suffix required for VaultAuth configuration
#
namePrefix: scheduler-web-
nameSuffix: -review

# Facilitate kustomization name updating
#
configurations:
  - kustomizeconfig.yaml

commonAnnotations:
  version: ${GIT_TAG:=stable}

images:
  - name: scheduler-web
    newName: ${IMAGE_NAME:=registry.ltc.bcit.ca/web-apps/openlab-scheduler/scheduler-web}
    newTag: ${IMAGE_TAG:=stable}

# Patches ingress with branch name as the subdomain"
#
patches:
  - target:
      kind: Ingress
    path: ingress-patch.yaml

  # Adjusts secrets for review branches
  - target:
      kind: Deployment
    path: deployment-patch.yaml

  # Incorporate vault-secrets
  #
  # adds `-review` suffix to VaultAuth `spec.mount`
  - target:
      kind: VaultAuth
    path: vault-secrets-review/vault-auth-patch.yaml

components:
  # Include environment-specific secrets
  # - ./vault-secrets-review # - Review branch secrets generated below

  # Required for VaultAuth role and serviceaccounts
  - ../../base/components/vault-auth

configMapGenerator:
  # Review branches connect to `latest` API by default
  #
  - name: api-config
    literals:
      - API_URL=https://latest--scheduler-api.ltc.bcit.ca/api/
    behavior: replace

  # Review branches use a unique SAML issuer
  #
  - name: saml-config
    literals:
      - SAML_ISSUER=scheduler-web--${DEPLOY_NAMESPACE}
      - SAML_CALLBACK_URL=${APP_URL}auth/login/callback
    behavior: merge

secretGenerator:
  - name: admin-credentials
    literals:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=password123

  - name: auth-signing-key
    literals:
      - JWT_AUTH_SIGNING_KEY=insecureT0kenSigningKey
