apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


# Flux envsubst replaces variables found in `deploy-vars.env` or falls back to defaults
#
namespace: ${DEPLOY_NAMESPACE:=scheduler-web}

resources:
- ../../base


# Resource names in a shared namespace must be unique
#
namePrefix: scheduler-web-

commonLabels:
  environment: review

commonAnnotations:
  version: ${GIT_TAG:=stable}

images:
- name: scheduler-web
  newName: ${IMAGE_NAME:=registry.ltc.bcit.ca/web-apps/openlab-scheduler/scheduler-web}
  newTag: ${IMAGE_TAG:=stable}


# Patches ingress with "review--"
#
patches:
- target:
    kind: Ingress
  path: ingress-patch.yaml

# # Create a .dockerconfig.json. Then uncomment this section for local cluster development.
# #
# - target:
#     kind: Deployment
#   patch: |-
#     - op: add
#       path: /spec/template/spec/imagePullSecrets
#       value: [name: gitlab-registry-credentials]


configMapGenerator:

  # Review branches connect to `latest` API by default
  #
  - name: api-config
    literals:
      - API_URL=https://latest--scheduler-api.ltc.bcit.ca/api/
    behavior: replace

  # Review branches use a unique SAML issuer
  #
  - name: saml-config
    literals:
      - SAML_ISSUER=review--${DEPLOY_NAMESPACE}--scheduler-web
      - SAML_CALLBACK_URL=${APP_URL}login/callback
    behavior: merge


# # Uncomment for local cluster development
#
# secretGenerator:
#
# - name: gitlab-registry-credentials
#   type: kubernetes.io/dockerconfigjson
#   files:
#     - .dockerconfigjson=secrets/.dockerconfig.json


# Inject secrets from Vault Secrets Operator
#    
components:
  - ./vault-secrets
