apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


# Flux envsubst replaces variables found in `deploy-vars.env` or falls back to defaults
#
namespace: ${DEPLOY_NAMESPACE:=scheduler-web}

resources:
- ../../base

commonLabels:
  environment: review

commonAnnotations:
  version: ${GIT_TAG:=stable}

images:
- name: scheduler-web
  newName: ${IMAGE_NAME:=registry.ltc.bcit.ca/web-apps/openlab-scheduler/scheduler-web}
  newTag: ${IMAGE_TAG:=stable}

patches:
- target:
    kind: Ingress
  path: ingress-patch.yaml
- target:
    kind: Deployment
  path: deployment-patch.yaml

# # Create a .dockerconfig.json. Then uncomment this section for local cluster development.
# #
# - target:
#     kind: Deployment
#   patch: |-
#     - op: add
#       path: /spec/template/spec/imagePullSecrets
#       value: [name: gitlab-registry-credentials]

secretGenerator:
  - name: vault-secrets-override
    literals:
      - LOCAL_USER=admin
      - LOCAL_PASSWORD=password123
      - SECRET_KEY=ahuaejsdb
  - name: oidc-secret
    literals:
      - CLIENT_ID=slGQesNqqYgOjuQsKrVoNkdO0NrF85zJ
      - CLIENT_SECRET=hvo_secret_T3lfFGtvhicYfjBmEEq8ydwpjucImDYLlPZvGSo9MHvU75EZTT4btqm4iBhi3p8n

configMapGenerator:
  - name: api-config
    literals:
      - API_URL=https://latest--scheduler-api.ltc.bcit.ca/api/
    behavior: merge
  - name: oidc-config
    literals:
      - ISSUER=https://vault.ltc.bcit.ca/v1/identity/oidc/provider/ltc-auth
      - AUTHORIZATION_URL=https://vault.ltc.bcit.ca/ui/vault/identity/oidc/provider/ltc-auth/authorize
      - TOKEN_URL=https://vault.ltc.bcit.ca/v1/identity/oidc/provider/ltc-auth/token
      - USERINFO_URL=https://vault.ltc.bcit.ca/v1/identity/oidc/provider/ltc-auth/userinfo
      - CALLBACK_URL=http://localhost:9000/login/callback


# # Uncomment for local cluster development
# #
# - name: gitlab-registry-credentials
#   type: kubernetes.io/dockerconfigjson
#   files:
#     - .dockerconfigjson=secrets/.dockerconfig.json
