apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


# Flux envsubst replaces variables found in `deploy-vars.env` or falls back to defaults
#
namespace: ${DEPLOY_NAMESPACE:=scheduler-web}

resources:
- ../../base

commonLabels:
  environment: review

commonAnnotations:
  version: ${GIT_TAG:=stable}

images:
- name: scheduler-web
  newName: ${IMAGE_NAME:=registry.ltc.bcit.ca/web-apps/openlab-scheduler/scheduler-web}
  newTag: ${IMAGE_TAG:=stable}

patches:
- target:
    kind: Ingress
  path: ingress-patch.yaml
- target:
    kind: Deployment
  path: deployment-patch.yaml

# # Create a .dockerconfig.json. Then uncomment this section for local cluster development.
# #
# - target:
#     kind: Deployment
#   patch: |-
#     - op: add
#       path: /spec/template/spec/imagePullSecrets
#       value: [name: gitlab-registry-credentials]

secretGenerator:
  - name: vault-secrets-override
    literals:
      - LOCAL_USER=admin
      - LOCAL_PASSWORD=password123
      - SECRET_KEY=ahuaejsdb
  - name: idp-cert
    files:
    - secrets/idp.crt

configMapGenerator:
  - name: saml-authsources
    data:
      saml_authsources.php: |
        <?php
        $config = array(
            'admin' => array(
                'core:AdminPassword',
            ),
            //admin creds for the idp server itself => usn:admin /	pw:secret
            'example-userpass' => array(
                'exampleauth:UserPass',
                'admin@bcit.ca:admin' => array(
                    'email' => 'admin@bcit.ca',
                    'firstname' => 'firstadmin firstname',
                    'lastname' => 'firstadmin lastname',
                    'type' => 'non-student', # in reality it could be "employee" or "instructor" or any other non student fields
                    'program' => 'BSN' # the exact name in the field is not know so use BSN for now
                ),
                'nextadmin@bcit.ca:admin' => array(
                    'email' => 'nextadmin@bcit.ca',
                    'firstname' => 'nextadmin firstname',
                    'lastname' => 'nextadmin lastname',
                    'type' => 'non-student', # in reality it could be "employee" or "instructor" or any other non student fields
                    'program' => 'BSN' # the exact name in the field is not know so use BSN for now
                ),
                'student1@bcit.ca:student' => array(
                    'email' => 'student1@bcit.ca',
                    'firstname' => 'student1 firstname',
                    'lastname' => 'student1 lastname',
                    'type' => 'student',
                    'program' => 'BSN'
                ),
                'student2@bcit.ca:student' => array(
                    'email' => 'student2@bcit.ca',
                    'firstname' => 'student2 firstname',
                    'lastname' => 'student2 lastname',
                    'type' => 'student',
                    'program' => 'BSN'
                ),
                'student3@bcit.ca:student' => array(
                    'email' => 'student3@bcit.ca',
                    'firstname' => 'student3 firstname',
                    'lastname' => 'student3 lastname',
                    'type' => 'student',
                    'program' => 'BSN'
                )
            ),
        );

  # # Uncomment for local cluster development
  # #
  # - name: gitlab-registry-credentials
  #   type: kubernetes.io/dockerconfigjson
  #   files:
  #     - .dockerconfigjson=secrets/.dockerconfig.json
