apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scheduler-web
  template:
    metadata:
      annotations:
        config.linkerd.io/skip-outbound-ports: "443"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "scheduler-web-kubeauthbot-stable"
        vault.hashicorp.com/agent-inject-secret-config: "web-apps/data/scheduler-web"
        vault.hashicorp.com/agent-inject-template-config: |
          {{ with secret "web-apps/data/scheduler-web" -}}
          SECRET_KEY="{{ .Data.data.SECRET_KEY }}"

          {{- end }}
    spec:
      containers:
        - name: scheduler-web
          env:
            - name: ELASTIC_APM_SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: elasticapm-config
                  key: ELASTIC_APM_SERVICE_NAME
