apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - public-endpoint.yaml
commonLabels:
  environment: stable
# Prefix/Suffix required for VaultAuth configuration
#
namePrefix: scheduler-web-
nameSuffix: -stable
# Teach kustomize how to update generated names
#
configurations:
  - kustomizeconfig.yaml
commonAnnotations:
  version: 1.1.0 # {"$imagepolicy": "openlab-scheduler:scheduler-web-image-policy-stable:tag"}
images:
  - name: "scheduler-web"
    newName: "registry.ltc.bcit.ca/web-apps/openlab-scheduler/scheduler-web"
    newTag: "1.1.0" # {"$imagepolicy": "openlab-scheduler:scheduler-web-image-policy-stable:tag"}
patches:
  # Patches deployment with secrets
  - target:
      kind: Deployment
    path: deployment-patch.yaml
  # Incorporate vault-secrets
  #
  # adds `-stable` suffix to VaultAuth `spec.mount`
  - target:
      kind: VaultAuth
    path: vault-secrets-stable/vault-auth-patch.yaml
components:
  # Include environment-specific secrets
  - ./vault-secrets-stable
  # Required for VaultAuth role and serviceaccounts
  - ../../base/components/vault-auth
configMapGenerator:
  # Updates elasticapm config
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVICE_NAME=openlab-scheduler
    behavior: merge
# Alternate API backend location
# - name: api-config
#   literals:
#     - API_URL=https://latest--scheduler-api.ltc.bcit.ca/api/
# SAML config
#
# Alternate Keycloak SAML idP
# - name: saml-config
#   literals:
#     - SAML_IDENTITY_PROVIDER_URL=https://latest--keycloak.ltc.bcit.ca/realms/ltc/protocol/saml
