apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openlab-scheduler
resources:
  - ../../base
  - alternate-ingress.yaml
commonLabels:
  environment: stable
commonAnnotations:
  version: 1.0.4 # {"$imagepolicy": "openlab-scheduler:scheduler-web-image-policy:tag"}
images:
  - name: "scheduler-web"
    newName: "registry.ltc.bcit.ca/web-apps/openlab-scheduler/scheduler-web"
    newTag: "1.0.4" # {"$imagepolicy": "openlab-scheduler:scheduler-web-image-policy:tag"}
# Adds elasticapm config and Vault agent annotations to deployment
#
patches:
  - target:
      kind: Deployment
    path: deployment-patch.yaml
# Generates elasticapm config
#
configMapGenerator:
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVICE_NAME=scheduler-web-stable
    behavior: merge
  - name: api-config
    literals:
      - API_URL=https://scheduler-api.ltc.bcit.ca/api/
    behavior: replace
