# This file is for teaching kustomize how to substitute names in the CRD
#
---
nameReference:
  - kind: VaultStaticSecret
    fieldSpecs:
      - kind: Deployment
        path: spec/template/spec/containers/envFrom/secretRef/name
      - kind: VaultStaticSecret
        path: spec/destination/name

  # Ensure Ingress backend service name matches the service
  - kind: VaultStaticSecret
    fieldSpecs:
      - path: spec/tls/secretName
        kind: Ingress
