apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-web
  template:
    metadata:
      labels:
        app: scheduler-web
    spec:
      serviceAccountName: serviceaccount
      containers:
        - name: scheduler-web
          image: scheduler-web
          envFrom:
            - configMapRef:
                name: elasticapm-config
            - configMapRef:
                name: api-config
            - configMapRef:
                name: saml-config
          # readinessProbe:
          #   tcpSocket:
          #     port: 8000
          #   initialDelaySeconds: 20
          #   periodSeconds: 30
          # livenessProbe:
          #   tcpSocket:
          #     port: 8000
          #   initialDelaySeconds: 15
          #   periodSeconds: 30
          ports:
            - containerPort: 9000
              protocol: TCP
          volumeMounts:
            - name: keycloak-ltc-realm-idp-cert
              mountPath: /app/saml
      volumes:
        - name: keycloak-ltc-realm-idp-cert
          secret:
            secretName: keycloak-ltc-realm-idp-cert
