apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: scheduler-web-

resources:
  - deployment.yaml
  - ingress.yaml
  - serviceaccount.yaml

commonLabels:
  app: scheduler-web
  app.kubernetes.io/name: scheduler-web

secretGenerator:
  - name: initial-user-credentials
    literals:
      - INITIAL_USER=admin
      - INITIAL_PASSWORD=password123

configMapGenerator:
# Generates elasticapm config
#
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVER_URL=https://bcit-ltc.apm.westus2.azure.elastic-cloud.com
# Specify API backend location
#
  - name: api-config
    literals:
      - API_URL=scheduler-web.openlab-scheduler:8000/api/

