apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


# If workloads share a common namespace, set the `namePrefix` in the overlay
#   `kustomization.yaml` to avoid name collisions.
#
# namePrefix: scheduler-web-


resources:
  - deployment.yaml
  - ingress.yaml
  - serviceaccount.yaml
  - service.yaml
  
commonLabels:
  app: scheduler-web
  app.kubernetes.io/name: scheduler-web


configMapGenerator:

# Generates elasticapm config
#
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVER_URL=https://bcit-ltc.apm.westus2.azure.elastic-cloud.com

# Specify API backend location
#
  - name: api-config
    literals:
      - API_URL=https://scheduler-api.ltc.bcit.ca/api/

# Specify Keycloak SAML location
#
  - name: saml-config
    literals:
      - SAML_URL=https://keycloak.ltc.bcit.ca/realms/ltc/protocol/saml
