apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  - serviceaccount.yaml

commonLabels:
  app: scheduler-web
  app.kubernetes.io/name: scheduler-web

# Facilitate kustomization name updating
#
configurations:
  - kustomizeconfig.yaml

configMapGenerator:
  # Specify API backend location
  - name: api-config
    literals:
      - API_URL=https://scheduler-api.ltc.bcit.ca/api/

  # Generates elasticapm config
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVER_URL=https://bcit-ltc.apm.westus2.azure.elastic-cloud.com

  # Specify Keycloak SAML location
  - name: saml-config
    literals:
      - SAML_IDENTITY_PROVIDER_URL=https://keycloak.ltc.bcit.ca/realms/ltc/protocol/saml
      - SAML_ISSUER=scheduler-web
      - SAML_IDP_CERT=/app/saml/keycloak_idp.crt

