# This file is for teaching kustomize how to substitute names in the CRD
#
---
nameReference:
  - kind: ServiceAccount
    fieldSpecs:
      - path: spec/kubernetes/serviceAccount
        kind: VaultAuth

  - kind: VaultAuth
    fieldSpecs:
      - path: spec/vaultAuthRef
        kind: VaultStaticSecret

  - kind: VaultStaticSecret
    fieldSpecs:
      - kind: Deployment
        path: spec/template/spec/volumes/secret/secretName
