apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: saml-idp-certificate
spec:
  type: kv-v2
  mount: ltc-infrastructure
  path: keycloak/realm-config
  destination:
    name: saml-idp-certificate
    create: true
  refreshAfter: 6h
  vaultAuthRef: scheduler-web-kubeauthbot-latest