apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
spec:
  method: kubernetes
  mount: kubernetes-latest
  kubernetes:
    role: scheduler-web-kubeauthbot-latest
    serviceAccount: serviceaccount
    audiences:
      - vault
