# name: Docker Build Image and Deploy to Azure Container Registry
# on:
#   push:
#     branches: ["main"]
#   pull_request:
#     branches: ["main"]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:

#     - name: Checkout repo
#       uses: actions/checkout@v4

#     - name: Login to ACR
#       uses: docker/login-action@v3
#       with:
#         registry: ${{ secrets.AZURE_REGISTRY }}
#         username: ${{ secrets.AZURE_CLIENT_ID }}
#         password: ${{ secrets.AZURE_CLIENT_SECRET }}

#     - name: Build, tag, and push image to Azure Container Registry
#       env:
#         AZURE_REGISTRY: ${{ secrets.AZURE_REGISTRY }}
#         REPO_NAME: ${{ github.event.repository.name }}
#         IMAGE_TAG: latest
#       run: |
#         docker build -t $AZURE_REGISTRY/$REPO_NAME:$IMAGE_TAG .
#         docker push $AZURE_REGISTRY/$REPO_NAME:$IMAGE_TAG
