name: Trigger auto deployment for scheduler-web

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/scheduler-web-AutoDeployTrigger-a807f2dc-add9-4bd1-bb50-363aa65f5c62.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SCHEDULERWEB_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SCHEDULERWEB_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SCHEDULERWEB_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: bcitltc.azurecr.io
          registryUsername: ${{ secrets.SCHEDULERWEB_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SCHEDULERWEB_REGISTRY_PASSWORD }}
          containerAppName: scheduler-web
          resourceGroup: LTC-ResourceGroup-CA
          imageToBuild: bcitltc.azurecr.io/scheduler-web:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


